#!/bin/sh

# cloudant credentials generated by bluemix
CLOUDANT_USERNAME=
CLOUDANT_PASSWORD=

# name of database
DATABASE=products

# input validation
if [ -z "${CLOUDANT_USERNAME}" ]; then
    echo "Please provide your CLOUDANT_USERNAME."
    exit
fi
if [ -z "${CLOUDANT_PASSWORD}" ]; then
    echo "Please provide your CLOUDANT_PASSWORD."
    exit
fi

# credentials to post data to cloudant
AUTH="$(python -c 'import base64; print base64.urlsafe_b64encode("'${CLOUDANT_USERNAME}':'${CLOUDANT_PASSWORD}'")')"
ACURL="curl -s --proto '=https' -iv -g -H 'Authorization: Basic ${AUTH}'"
HOST="https://${CLOUDANT_USERNAME}.cloudant.com"

# dynamically generate security file for cloudant
cat > security.json << EOF
{
  "cloudant": {
    "${CLOUDANT_USERNAME}": [
      "_reader",
      "_writer",
      "_admin",
      "_replicator"
    ],
    "nobody": ["_reader"]
  }
}
EOF

# uploads to cloudant
eval ${ACURL} -X DELETE '${HOST}/${DATABASE}'
eval ${ACURL} -X PUT '${HOST}/${DATABASE}'
eval ${ACURL} -H "Content-Type:application/json" -d @${DATABASE}.json -vX POST '${HOST}/${DATABASE}/_bulk_docs'
eval ${ACURL} -H "Content-Type:application/json" -d @security.json -vX PUT '${HOST}/${DATABASE}/_security'
